### PR TITLE
musicbeeUninstall.ahk Edit

### PR DESCRIPTION
**Pull request by anggaaja**
Edited as per instruction from dtgm:
- Replaced WinActivate+Keyboard emulation with ControlClick for mouse
  emulation

### CODE REVIEW

**Comment by brutaldev** [comment]
@anggaaja  Do you have a Chocolatey login name? I want to add you as a package maintainer so you can upload new versions.

**Comment by anggaaja** [comment]
It's "angga"

Thanks!

**Comment by brutaldev** [comment]
@anggaaja Added you as a maintainer, let me know if you're happy to submit the package.

**Comment by anggaaja** [comment]
I'll be more than happy. Thanks!

**Pull request merged**
